/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OracleBD;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.border.TitledBorder;

/**
 *
 * @author alumno
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
	initComponents();
	controlesVisualAcept.setVisible(Boolean.FALSE);
	crearConexionBD();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTab = new javax.swing.JTabbedPane();
        tabPrincipal = new javax.swing.JPanel();
        panelGestionDiaria = new javax.swing.JPanel();
        botonGesDepart = new javax.swing.JButton();
        botonGesEmple = new javax.swing.JButton();
        panelMantenimiento = new javax.swing.JPanel();
        LabelMainHead = new javax.swing.JLabel();
        tabDepartamentos = new javax.swing.JPanel();
        etiquetaSeccion = new javax.swing.JLabel();
        panelInfo = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        labelLocDept = new javax.swing.JLabel();
        TFLocDept = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        labelNomDept = new javax.swing.JLabel();
        TFNomDept = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        labelIdDept = new javax.swing.JLabel();
        TFIdDept = new javax.swing.JTextField();
        panelControles = new javax.swing.JPanel();
        controlesVisual = new javax.swing.JPanel();
        bAnterior = new javax.swing.JButton();
        bSiguiente = new javax.swing.JButton();
        bPrimero = new javax.swing.JButton();
        bUltimo = new javax.swing.JButton();
        controlesVisualAcept = new javax.swing.JPanel();
        botonCancelar = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        bInsertar = new javax.swing.JButton();
        bModificar = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        tabEmpleados = new javax.swing.JPanel();
        JPInfoEmple = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TFNumEmp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TFApeEmp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TFOfiEmp = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TFSalEmp = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        TFComEmp = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TFFAltEmp = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        CBDeptEmp = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        CBDirEmp = new javax.swing.JComboBox<>();
        BInicio = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        JPConIns = new javax.swing.JPanel();
        BConsultar = new javax.swing.JButton();
        BInsertar = new javax.swing.JButton();
        JPModEliminar = new javax.swing.JPanel();
        BEliminar = new javax.swing.JButton();
        BModificar = new javax.swing.JButton();
        JPAceptarCancelar = new javax.swing.JPanel();
        BAceptar = new javax.swing.JButton();
        BCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        panelTab.setPreferredSize(new java.awt.Dimension(611, 362));

        panelGestionDiaria.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder()), "Gestion Diaria", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        botonGesDepart.setText("Gestion de departamentos");
        botonGesDepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGesDepartActionPerformed(evt);
            }
        });

        botonGesEmple.setText("Gestion de empleados");
        botonGesEmple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGesEmpleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGestionDiariaLayout = new javax.swing.GroupLayout(panelGestionDiaria);
        panelGestionDiaria.setLayout(panelGestionDiariaLayout);
        panelGestionDiariaLayout.setHorizontalGroup(
            panelGestionDiariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGestionDiariaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGestionDiariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonGesEmple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonGesDepart, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelGestionDiariaLayout.setVerticalGroup(
            panelGestionDiariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGestionDiariaLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(botonGesDepart)
                .addGap(45, 45, 45)
                .addComponent(botonGesEmple)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        panelMantenimiento.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder()), "Mantenimiento", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        panelMantenimiento.setPreferredSize(new java.awt.Dimension(284, 297));

        javax.swing.GroupLayout panelMantenimientoLayout = new javax.swing.GroupLayout(panelMantenimiento);
        panelMantenimiento.setLayout(panelMantenimientoLayout);
        panelMantenimientoLayout.setHorizontalGroup(
            panelMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 284, Short.MAX_VALUE)
        );
        panelMantenimientoLayout.setVerticalGroup(
            panelMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        LabelMainHead.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelMainHead.setText("Aplicación Gestíon Acceso a Datos");

        javax.swing.GroupLayout tabPrincipalLayout = new javax.swing.GroupLayout(tabPrincipal);
        tabPrincipal.setLayout(tabPrincipalLayout);
        tabPrincipalLayout.setHorizontalGroup(
            tabPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelMainHead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tabPrincipalLayout.createSequentialGroup()
                        .addComponent(panelGestionDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelMantenimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tabPrincipalLayout.setVerticalGroup(
            tabPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabPrincipalLayout.createSequentialGroup()
                .addComponent(LabelMainHead, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelGestionDiaria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMantenimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelTab.addTab("Principal", tabPrincipal);
        tabPrincipal.getAccessibleContext().setAccessibleName("");

        tabDepartamentos.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tabDepartamentosComponentShown(evt);
            }
        });

        etiquetaSeccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaSeccion.setText("Gestion de Departamentos");

        panelInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder()), "", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.BOTTOM));

        jPanel3.setPreferredSize(new java.awt.Dimension(112, 33));

        labelLocDept.setText("Localidad Departamento:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLocDept)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TFLocDept, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(labelLocDept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TFLocDept, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setPreferredSize(new java.awt.Dimension(113, 33));

        labelNomDept.setText("Nombre Departamento:");

        TFNomDept.setPreferredSize(new java.awt.Dimension(250, 19));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNomDept)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TFNomDept, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(labelNomDept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TFNomDept, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        labelIdDept.setText("ID Departamento:");
        labelIdDept.setMaximumSize(null);

        TFIdDept.setPreferredSize(new java.awt.Dimension(250, 19));
        TFIdDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFIdDeptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelIdDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TFIdDept, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(labelIdDept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TFIdDept, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout panelInfoLayout = new javax.swing.GroupLayout(panelInfo);
        panelInfo.setLayout(panelInfoLayout);
        panelInfoLayout.setHorizontalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelInfoLayout.setVerticalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelControles.setPreferredSize(new java.awt.Dimension(405, 41));

        bAnterior.setText("<");
        bAnterior.setPreferredSize(new java.awt.Dimension(48, 31));
        bAnterior.setRequestFocusEnabled(false);
        bAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnteriorActionPerformed(evt);
            }
        });

        bSiguiente.setText(">");
        bSiguiente.setPreferredSize(new java.awt.Dimension(48, 31));
        bSiguiente.setRequestFocusEnabled(false);
        bSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSiguienteActionPerformed(evt);
            }
        });

        bPrimero.setText("|<");
        bPrimero.setPreferredSize(new java.awt.Dimension(48, 31));
        bPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPrimeroActionPerformed(evt);
            }
        });

        bUltimo.setText(">|");
        bUltimo.setPreferredSize(new java.awt.Dimension(48, 31));
        bUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUltimoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlesVisualLayout = new javax.swing.GroupLayout(controlesVisual);
        controlesVisual.setLayout(controlesVisualLayout);
        controlesVisualLayout.setHorizontalGroup(
            controlesVisualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlesVisualLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(bPrimero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        controlesVisualLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bAnterior, bPrimero, bSiguiente, bUltimo});

        controlesVisualLayout.setVerticalGroup(
            controlesVisualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlesVisualLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(controlesVisualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bPrimero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        controlesVisualLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bAnterior, bPrimero, bSiguiente, bUltimo});

        botonCancelar.setText("Cancelar");
        botonCancelar.setPreferredSize(new java.awt.Dimension(48, 31));
        botonCancelar.setRequestFocusEnabled(false);
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.setPreferredSize(new java.awt.Dimension(48, 31));
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlesVisualAceptLayout = new javax.swing.GroupLayout(controlesVisualAcept);
        controlesVisualAcept.setLayout(controlesVisualAceptLayout);
        controlesVisualAceptLayout.setHorizontalGroup(
            controlesVisualAceptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlesVisualAceptLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(botonAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        controlesVisualAceptLayout.setVerticalGroup(
            controlesVisualAceptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlesVisualAceptLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(controlesVisualAceptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout panelControlesLayout = new javax.swing.GroupLayout(panelControles);
        panelControles.setLayout(panelControlesLayout);
        panelControlesLayout.setHorizontalGroup(
            panelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelControlesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(controlesVisualAcept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(controlesVisual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        panelControlesLayout.setVerticalGroup(
            panelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(controlesVisualAcept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(controlesVisual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bInsertar.setText("Insertar");
        bInsertar.setPreferredSize(new java.awt.Dimension(94, 51));
        bInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInsertarActionPerformed(evt);
            }
        });

        bModificar.setText("Modificar");
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });

        bEliminar.setText("Eliminar");
        bEliminar.setPreferredSize(new java.awt.Dimension(99, 25));
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(bInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(bModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(bEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout tabDepartamentosLayout = new javax.swing.GroupLayout(tabDepartamentos);
        tabDepartamentos.setLayout(tabDepartamentosLayout);
        tabDepartamentosLayout.setHorizontalGroup(
            tabDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDepartamentosLayout.createSequentialGroup()
                .addGroup(tabDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabDepartamentosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(tabDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(etiquetaSeccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(tabDepartamentosLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(panelControles, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(tabDepartamentosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tabDepartamentosLayout.setVerticalGroup(
            tabDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDepartamentosLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(etiquetaSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelControles, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelTab.addTab("Departamentos", tabDepartamentos);

        tabEmpleados.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tabEmpleadosComponentShown(evt);
            }
        });

        JPInfoEmple.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Empleado", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jLabel1.setText("Numero:");

        jLabel2.setText("Apellido:");

        jLabel3.setText("Oficio:");

        jLabel10.setText("Salario:");

        jLabel12.setText("Comision:");

        jLabel13.setText("Fecha Alta:");

        TFFAltEmp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        TFFAltEmp.setText("dd/mm/yy");

        jLabel4.setText("Departamento:");

        CBDeptEmp.setToolTipText("");
        CBDeptEmp.setName(""); // NOI18N

        jLabel5.setText("Director: ");

        javax.swing.GroupLayout JPInfoEmpleLayout = new javax.swing.GroupLayout(JPInfoEmple);
        JPInfoEmple.setLayout(JPInfoEmpleLayout);
        JPInfoEmpleLayout.setHorizontalGroup(
            JPInfoEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPInfoEmpleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPInfoEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPInfoEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CBDirEmp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CBDeptEmp, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TFNumEmp, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addComponent(TFApeEmp)
                    .addComponent(TFOfiEmp)
                    .addComponent(TFSalEmp)
                    .addComponent(TFComEmp)
                    .addComponent(TFFAltEmp))
                .addContainerGap())
        );
        JPInfoEmpleLayout.setVerticalGroup(
            JPInfoEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPInfoEmpleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JPInfoEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TFNumEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPInfoEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TFApeEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPInfoEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TFOfiEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPInfoEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TFSalEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPInfoEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(TFComEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPInfoEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(TFFAltEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPInfoEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBDeptEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPInfoEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBDirEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        JPInfoEmpleLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {TFComEmp, TFFAltEmp, TFSalEmp});

        BInicio.setText("Inicio");

        BConsultar.setText("Consultar");
        BConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BConsultarActionPerformed(evt);
            }
        });

        BInsertar.setText("Insertar");

        javax.swing.GroupLayout JPConInsLayout = new javax.swing.GroupLayout(JPConIns);
        JPConIns.setLayout(JPConInsLayout);
        JPConInsLayout.setHorizontalGroup(
            JPConInsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPConInsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPConInsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BInsertar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                .addContainerGap())
        );
        JPConInsLayout.setVerticalGroup(
            JPConInsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPConInsLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(BConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPConInsLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BConsultar, BInsertar});

        BEliminar.setText("Eliminar");

        BModificar.setText("Modificar");

        BAceptar.setText("Aceptar");

        BCancelar.setText("Cancelar");

        javax.swing.GroupLayout JPAceptarCancelarLayout = new javax.swing.GroupLayout(JPAceptarCancelar);
        JPAceptarCancelar.setLayout(JPAceptarCancelarLayout);
        JPAceptarCancelarLayout.setHorizontalGroup(
            JPAceptarCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPAceptarCancelarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPAceptarCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(BCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        JPAceptarCancelarLayout.setVerticalGroup(
            JPAceptarCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPAceptarCancelarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BAceptar)
                .addGap(18, 18, 18)
                .addComponent(BCancelar)
                .addContainerGap())
        );

        javax.swing.GroupLayout JPModEliminarLayout = new javax.swing.GroupLayout(JPModEliminar);
        JPModEliminar.setLayout(JPModEliminarLayout);
        JPModEliminarLayout.setHorizontalGroup(
            JPModEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPModEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPModEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(BEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(JPAceptarCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JPModEliminarLayout.setVerticalGroup(
            JPModEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPModEliminarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(BModificar)
                .addGap(18, 18, 18)
                .addComponent(BEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JPAceptarCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        JPModEliminarLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BEliminar, BModificar});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPModEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JPConIns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(JPConIns, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPModEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tabEmpleadosLayout = new javax.swing.GroupLayout(tabEmpleados);
        tabEmpleados.setLayout(tabEmpleadosLayout);
        tabEmpleadosLayout.setHorizontalGroup(
            tabEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPInfoEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        tabEmpleadosLayout.setVerticalGroup(
            tabEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JPInfoEmple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tabEmpleadosLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)))
                .addContainerGap())
        );

        panelTab.addTab("Empleados", tabEmpleados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("tab1");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGesDepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGesDepartActionPerformed
	panelTab.setSelectedComponent(this.tabDepartamentos);
    }//GEN-LAST:event_botonGesDepartActionPerformed

    private void botonGesEmpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGesEmpleActionPerformed
	panelTab.setSelectedComponent(this.tabEmpleados);
    }//GEN-LAST:event_botonGesEmpleActionPerformed

    private void bPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPrimeroActionPerformed
	try {
	    resultCompartido.first();
	} catch (SQLException ex) {
	    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
	}
	mostrarCamposDepartamentos();
    }//GEN-LAST:event_bPrimeroActionPerformed

    private void TFIdDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFIdDeptActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_TFIdDeptActionPerformed

    private void tabDepartamentosComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tabDepartamentosComponentShown
	restaurarDept();
	/*Statement sentencia = conexion.createStatement();
	    String sql = "SELECT * FROM departamentos";
	    resultCompartido = sentencia.executeQuery(sql);
	    resultCompartido.last();
	    maxTamResultSet = resultCompartido.getRow();
	    resultCompartido.first();
	    mostrarCamposDepartamentos();*/
    }//GEN-LAST:event_tabDepartamentosComponentShown

    private void bUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUltimoActionPerformed
	try {
	    resultCompartido.last();
	} catch (SQLException ex) {
	    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
	}
	mostrarCamposDepartamentos();
    }//GEN-LAST:event_bUltimoActionPerformed

    private void bInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInsertarActionPerformed
	TFIdDept.setEditable(Boolean.TRUE);
	TFNomDept.setEditable(Boolean.TRUE);
	TFLocDept.setEditable(Boolean.TRUE);
	((TitledBorder) panelInfo.getBorder()).setTitle("Nuevo Departamento");
	panelInfo.repaint();
	controlesVisual.setVisible(Boolean.FALSE);
	controlesVisualAcept.setVisible(Boolean.TRUE);
	limpiarCamposDepartamento();
    }//GEN-LAST:event_bInsertarActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
	try {
	    if (TFIdDept.isEditable()) {
		String sql = String.format(
			"INSERT INTO departamentos VALUES('%s', '%s', '%s')",
			TFIdDept.getText(), TFNomDept.getText(), TFLocDept.getText());

		Statement sentencia = conexion.createStatement();
		int numInsertados = sentencia.executeUpdate(sql);
		restaurarDept();
		if (numInsertados > 0) {
		    JOptionPane.showMessageDialog(tabDepartamentos, "Insertado Correctamente");
		} else {
		    JOptionPane.showMessageDialog(tabDepartamentos, "No se ha podido insertar");
		}
	    } else {
		Statement sentencia = conexion.createStatement();
		String sql = String.format(
			"UPDATE departamentos SET dnombre='%s', loc='%s' WHERE dept_no='%s'",
			TFNomDept.getText(), TFLocDept.getText(), TFIdDept.getText());
		int numInsertados = sentencia.executeUpdate(sql);
		restaurarDept();
		if (numInsertados > 0) {
		    JOptionPane.showMessageDialog(tabDepartamentos, "Modificado Correctamente");
		} else {
		    JOptionPane.showMessageDialog(tabDepartamentos, "No se ha podido modificar");
		}
	    }

	} catch (SQLException ex) {
	    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
	}
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void bSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSiguienteActionPerformed
	try {
	    if (resultCompartido.getRow() < maxTamResultSet) {
		resultCompartido.next();
	    }
	} catch (SQLException ex) {
	    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
	}
	mostrarCamposDepartamentos();
    }//GEN-LAST:event_bSiguienteActionPerformed

    private void bAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnteriorActionPerformed
	try {
	    if (resultCompartido.getRow() > 1) {
		resultCompartido.previous();
	    }
	} catch (SQLException ex) {
	    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
	}
	mostrarCamposDepartamentos();
    }//GEN-LAST:event_bAnteriorActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
	restaurarDept();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
	controlesVisual.setVisible(Boolean.FALSE);
	controlesVisualAcept.setVisible(Boolean.TRUE);
	TFLocDept.setEditable(Boolean.TRUE);
	TFNomDept.setEditable(Boolean.TRUE);
	controlesVisualAcept.setVisible(Boolean.TRUE);
    }//GEN-LAST:event_bModificarActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
	if (JOptionPane.showConfirmDialog(tabDepartamentos, "¿Desea borrar el departamento: " + TFNomDept.getText()) == 0) {
	    try {
		Statement sentencia = conexion.createStatement();
		String sql = String.format("DELETE FROM departamentos WHERE dept_no='%s'", TFIdDept.getText());
		if (sentencia.executeUpdate(sql) > 0) {
		    JOptionPane.showMessageDialog(tabDepartamentos, "El departamento "+TFNomDept.getText()+" ha sido borrado.");
		}
	    } catch (SQLException ex) {
		Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
	    }finally{
		restaurarDept();
	    }
	}
    }//GEN-LAST:event_bEliminarActionPerformed

    private void tabEmpleadosComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tabEmpleadosComponentShown
	toogleEditableTFEmple();
	if(JPAceptarCancelar.isVisible()){
	    toogleMostarAceptarCancelar();
	}
	if(JPModEliminar.isVisible()){
	    toogleMostrarModificarEliminar();
	}
	
    }//GEN-LAST:event_tabEmpleadosComponentShown

    private void BConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BConsultarActionPerformed
        if(!TFNumEmp.getText().isEmpty()){
	    mostrarCamposEmpleado();
	}
    }//GEN-LAST:event_BConsultarActionPerformed
    private void mostrarCamposEmpleado(){
	try {
		String sql = "SELECT * FROM empleados WHERE emp_no=?";
		PreparedStatement pStatement = conexion.prepareStatement(sql);
		pStatement.setInt(1, Integer.parseInt(TFNumEmp.getText()));
		ResultSet result = pStatement.executeQuery();
		if(result.next()){
		    toogleMostrarModificarEliminar();
		    TFApeEmp.setText(result.getString("apellido"));
		    TFOfiEmp.setText(result.getString("oficio"));
		    TFSalEmp.setText(String.valueOf(result.getDouble("salario")));
		    TFComEmp.setText(String.valueOf(result.getDouble("comision")));
		    CBDirEmp.removeAllItems();
		    CBDirEmp.addItem(String.valueOf(result.getInt("dir")));
		    String fecha = null;
		    try {
			fecha = TFFAltEmp.getFormatter().valueToString(result.getDate("fecha_alt"));
		    } catch (ParseException ex) {
			Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
		    }
		    TFFAltEmp.setText(fecha);
		    
		    sql = "SELECT dnombre FROM departamentos WHERE dept_no = ?";
		    pStatement = conexion.prepareStatement(sql);
		    pStatement.setInt(1,result.getInt("dept_no"));
		    result = pStatement.executeQuery();
		    if(result.next()){
			CBDeptEmp.addItem(result.getString(1));
		    }
		}else{
		    JOptionPane.showMessageDialog(tabEmpleados, "El id no se encuentra en nuestra BBDD");
		}
		
	    } catch (SQLException ex) {
		Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
	    }
	    
	    
    }
    
    private void toogleEditableTFEmple(){
	if(TFNomDept.isEditable()){
	    TFNomDept.setEditable(Boolean.FALSE);
	    TFOfiEmp.setEditable(Boolean.FALSE);
	    TFSalEmp.setEditable(Boolean.FALSE);
	    TFComEmp.setEditable(Boolean.FALSE);
	    TFFAltEmp.setEditable(Boolean.FALSE);
	    CBDeptEmp.setEditable(Boolean.FALSE);
	    CBDirEmp.setEditable(Boolean.FALSE);
	}
    }
    private void toogleMostrarModificarEliminar(){
	if(JPModEliminar.isVisible()){
	    JPModEliminar.setVisible(Boolean.FALSE);
	}else{
	    JPModEliminar.setVisible(Boolean.TRUE);
	}
    }
    
    private void toogleMostarAceptarCancelar(){
	if(JPAceptarCancelar.isVisible()){
	    JPAceptarCancelar.setVisible(Boolean.FALSE);
	}else{
	    JPAceptarCancelar.setVisible(Boolean.TRUE);
	}
    }
    private void mostrarCamposDepartamentos() {
	try {
	    ((TitledBorder) panelInfo.getBorder()).setTitle(
		    String.valueOf(resultCompartido.getRow())
		    + "/" + String.valueOf(maxTamResultSet));
	    panelInfo.repaint();
	    TFIdDept.setText(String.valueOf(resultCompartido.getInt("dept_no")));
	    TFNomDept.setText(resultCompartido.getString("dnombre"));
	    TFLocDept.setText(resultCompartido.getString("loc"));
	} catch (SQLException ex) {
	    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
	}
    }

    private void limpiarCamposDepartamento() {
	TFIdDept.setText("");
	TFNomDept.setText("");
	TFLocDept.setText("");
    }

    private void crearConexionBD() {
	try {
	    Class.forName("com.mysql.cj.jdbc.Driver");
	    conexion = DriverManager.getConnection("jdbc:mysql://localhost/MySQLDB.db?useSSL=false", "root", "sephir0th");

	} catch (ClassNotFoundException | SQLException ex) {
	    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
	}
    }

    private void restaurarDept() {
	try {
	    // TODO add your handling code here:
	    TFIdDept.setEditable(Boolean.FALSE);
	    TFLocDept.setEditable(Boolean.FALSE);
	    TFNomDept.setEditable(Boolean.FALSE);
	    controlesVisual.setVisible(Boolean.TRUE);
	    controlesVisualAcept.setVisible(Boolean.FALSE);
	    panelControles.repaint();
	    Statement sentencia = conexion.createStatement();
	    String sql = "SELECT * FROM departamentos";
	    resultCompartido = sentencia.executeQuery(sql);
	    resultCompartido.last();
	    maxTamResultSet = resultCompartido.getRow();
	    resultCompartido.first();
	    mostrarCamposDepartamentos();
	} catch (SQLException ex) {
	    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
	}
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new MainForm().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAceptar;
    private javax.swing.JButton BCancelar;
    private javax.swing.JButton BConsultar;
    private javax.swing.JButton BEliminar;
    private javax.swing.JButton BInicio;
    private javax.swing.JButton BInsertar;
    private javax.swing.JButton BModificar;
    private javax.swing.JComboBox<String> CBDeptEmp;
    private javax.swing.JComboBox<String> CBDirEmp;
    private javax.swing.JPanel JPAceptarCancelar;
    private javax.swing.JPanel JPConIns;
    private javax.swing.JPanel JPInfoEmple;
    private javax.swing.JPanel JPModEliminar;
    private javax.swing.JLabel LabelMainHead;
    private javax.swing.JTextField TFApeEmp;
    private javax.swing.JTextField TFComEmp;
    private javax.swing.JFormattedTextField TFFAltEmp;
    private javax.swing.JTextField TFIdDept;
    private javax.swing.JTextField TFLocDept;
    private javax.swing.JTextField TFNomDept;
    private javax.swing.JTextField TFNumEmp;
    private javax.swing.JTextField TFOfiEmp;
    private javax.swing.JTextField TFSalEmp;
    private javax.swing.JButton bAnterior;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bInsertar;
    private javax.swing.JButton bModificar;
    private javax.swing.JButton bPrimero;
    private javax.swing.JButton bSiguiente;
    private javax.swing.JButton bUltimo;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonGesDepart;
    private javax.swing.JButton botonGesEmple;
    private javax.swing.JPanel controlesVisual;
    private javax.swing.JPanel controlesVisualAcept;
    private javax.swing.JLabel etiquetaSeccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel labelIdDept;
    private javax.swing.JLabel labelLocDept;
    private javax.swing.JLabel labelNomDept;
    private javax.swing.JPanel panelControles;
    private javax.swing.JPanel panelGestionDiaria;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelMantenimiento;
    private javax.swing.JTabbedPane panelTab;
    private javax.swing.JPanel tabDepartamentos;
    private javax.swing.JPanel tabEmpleados;
    private javax.swing.JPanel tabPrincipal;
    // End of variables declaration//GEN-END:variables

    // Mis atributos
    private Connection conexion;
    private ResultSet resultCompartido;
    private int maxTamResultSet;
}
